ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
VIA_ENABLE = no
LTO_ENABLE = yes
RGBLIGHT_ENABLE = no
WPM_ENABLE = yes
OLED_ENABLE = yes

# Not necessary anymore
# OLED_DRIVER = SSD1306
# RGB_MATRIX_ENABLE = yes
# RGB_MATRIX_DRIVER = ws2812

POINTING_DEVICE_ENABLE = no
POINTING_DEVICE_DRIVER = pimoroni_trackball
MOUSEKEY_ENABLE = yes

DEBUG_ENABLE = no
CONSOLE_ENABLE = no
