ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
VIA_ENABLE = no
LTO_ENABLE = yes
RGBLIGHT_ENABLE = no
WPM_ENABLE = yes
OLED_ENABLE = yes
# OLED_DRIVER = SSD1306

MOUSEKEY_ENABLE = yes

# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = pimoroni_trackball
# MOUSEKEY_ENABLE = yes

DEBUG_ENABLE = no
CONSOLE_ENABLE = no